export const TOGGLE_MENU_VISIBILITY = "TOGGLE_MENU_VISIBILITY";
export const SET_SCROLL_TOP = "SET_SCROLL_TOP";
export const SET_INDEX = "SET_INDEX";
export const TOGGLE_DETAILED_INFO_VISIBILITY = "TOGGLE_DETAILED_INFO_VISIBILITY";
